name: Check Build
on: 
  push:
    paths:
      - '*.go'
      - 'go.mod'
      - 'go.sum'
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: Build Go
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.19', '1.20']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Run linter
      run: golangci-lint run

    - name: Run tests
      run: go test -v ./...

    - name: Build optimized binary
      env:
        CGO_ENABLED: 0
      run: |
        go build -v -ldflags="-s -w" .

    - name: Check Help
      run: go run -v ./... --help || true

    - name: Test Regex - Ends with 'GO'
      run: go run -v ./... --regex 'GO$'

    - name: Test Regex - Ends with 'SSH', insensitive
      run: go run -v ./... --insensitive --regex "SSH$"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sshchic-${{ matrix.os }}
        path: sshchic*
